### ISSUE TITLE
Fork to a submodule?

### ISSUE THREAD

**Issue by Manouchehri** [jonjonarnearne/smi2021#10]
Is there any particular reason to require the entire kernel history for a single module?

```
git clone https://github.com/jonjonarnearne/smi2021
cd smi2021/
git subtree split -P drivers/media/usb/smi2021 -b split2021
cd ../
mkdir new2021/ && cd new2021/
git pull ../smi2021 split2021
```

At this point, `split2021` will contain the bare module, which could be pushed back up. The downside is that the commit hashes are changed, but that seems like a better solution to me compared to cloning the entire kernel.

Example of what it looks like after:

https://github.com/Manouchehri/smi2021

**Comment by jonjonarnearne** [comment]
if you do that, you will lose the changes to the kconfig file i the parent
directory.

the reason i ended with the whole tree is that the driver also included
some changes to the saa7113 driver. those changes are now included in the
latest kernel releases.

**Comment by Manouchehri** [comment]
You could clone a level up and strip away the other files.

Personally, this is how I'm building it (writing this from memory, so it might not be 100% correct). I'm not using the kconfig.

```
cd drivers/media/usb/smi2021
sed -i '0,/obj/{s/$(CONFIG_VIDEO_SMI2021)/m/}' Makefile
make -C /lib/modules/$(uname -r)/build M=$PWD modules
install -Dm644 smi2021.ko /usr/lib/modules/$(printf extramodules-`pacman -Q linux | grep -Po "\d+\.\d+"`-ARCH)/
```

**Comment by Manouchehri** [comment]
I've done a bit of work merging and cleaning up the module into a new repository, feel free to check it out.

https://github.com/Manouchehri/smi2021
