### ISSUE TITLE
Can you see any change in parse_video

### ISSUE THREAD

**Issue by mastervolkov** [jonjonarnearne/smi2021#9]
Unable add pull reguest to you, but have some performance and get stable img

(I test on motion - and in 10 Fps they get laggy img - with thet patch - all work)

https://github.com/mastervolkov/smi2021/pull/1
or simple
master in https://github.com/mastervolkov/smi2021

**Comment by tosiara** [comment]
Hey, I also did have issues with motion and FPS 10, reported here: https://github.com/jonjonarnearne/smi2021/issues/7
Can you confirm you have had same issue?

**Comment by mastervolkov** [comment]
Yes. Sorry for my bad english.

Current trunk have some problem:
1. get_buf not allways return buffer, but if buffer adsent - start position
(buf->pos) lost (stay zero)- as result, first (odd) frame draw not from
first line.
I fix these - if buffer need, but not alloced - skip thet frame and send in
buffer next frame. Result is all frame good ( i test and use that in my
motion with 10 fps - all excellent - problem adsent
2. Copy_video do copy by 1 byte - thet not optimal - i change to memcpy
3. All line from device is 1440 ( performance improvement here) - i change
processing find trc to block 1440 + 3 = total (by oprofile) performance
faster at x20.

P.S. How i can get you driver/media/usb/smi2021 only for sending pull
request?
P.S. Which version somagic, smi2021, or easycap-somagick on github is last,
here send push request or how collaborate all in one for dev productivity?
01 апр. 2015 г. 8:10 пользователь "tosiara" notifications@github.com
написал:

**Comment by jonjonarnearne** [comment]
this sounds great.
I'll have a look at your tree later today and try to merge your fixes.

**Comment by mastervolkov** [comment]
All my change in patch in attach

i send that patch to
https://github.com/kerpz/smi2021
https://github.com/barneyman/somagic
https://github.com/barneyman/somagictoo

2015-04-01 9:20 GMT+03:00 Jon Arne Jørgensen notifications@github.com:

> this sounds great.
> I'll have a look at your tree later today and try to merge your fixes.
>

**Comment by tosiara** [comment]
@mastervolkov is it possible to compile just a module from your master branch? How do you compile?

**Comment by tosiara** [comment]
I tried just to replace files in @jonjonarnearne master branch - but I get kernel panic as soon as try to open device. Stack top is copy_video_block+0xc4/0x170, EIP is at memcpy+0x18/0x30:

![dsc_1254](https://cloud.githubusercontent.com/assets/3600973/6991951/d89e08b4-daba-11e4-9dd6-e7a0dad91487.JPG)

**Comment by mastervolkov** [comment]
I use kernel 3.17.7 with folder from https://github.com/mastervolkov/smi2021

But i try kernel jonjonarnearne with changed folder later

04 апр. 2015 г. 11:08 пользователь "tosiara" notifications@github.com
написал:

**Comment by jonjonarnearne** [comment]
I'm sorry but I haven't had time to merge the changes yet. I would really
like to help you, and I hope i get a chance to test your changes soon :)

**Comment by mastervolkov** [comment]
Thet change merged by Manouchehri in https://github.com/Manouchehri/smi2021/tree/staging

**Comment by mastervolkov** [comment]
tosiara can you reTest these in https://github.com/Manouchehri/smi2021/
